config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'post/index' => 'post#index', as: :post
  get 'post/genesis' => 'post#genesis', as: :genesis
  post 'post/genesis_post' => 'post#genesis_post', as: :genesis_post
  get 'post/one' => 'post#one', as: :one
  post 'post/new_comment' => 'post#new_comment', as: :new_comment

end

app/models/comment.rb
class Comment
  include Mongoid::Document

  field :author, type: String
  field :comment, type: String
  embedded_in :post
end

app/models/post.rb
class Post
  include Mongoid::Document

  field :title, type: String
  field :body, type: String

  embeds_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @posts = Post.all
  end

  def genesis
    @post = Post.new
  end

  def genesis_post
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path
    else
      redirect_to @post, notice: "There was an error creating posts."
    end
  end

  def one
    @post = Post.find(params[:post])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
here we go
<%= link_to 'Posts', post_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MongoMultiModel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/post/genesis.html.erb
<%= form_for(@post, :url => {:action => :genesis_post, :controller => :post}) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/post/index.html.erb
<table>
<thead>
  <tr>
    <th>Title</th>
    <th>Content</th>
  </tr>  
</thead>
<% @posts.each do |p| %>
  <tr>
  <td><%= p.title %></td>
  <td><%= p.body %></td>
  <td><%= link_to "Show", one_path(:post => post.id) %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'New Post', genesis_path %>